name: Deploy static site to Azure Web App - guilabs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write    # required for azure/login OIDC
      contents: read     # required for actions/checkout

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_5E17B640C4B84F5EAB3C0CC2D7D55B14 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_3E27FEF781AE449CB7B88862D8F5AE98 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B89A75E9BE614C94970CAC06D7D3840C }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'guilabs'
          slot-name: 'Production'
          package: .
